source 'https://rubygems.org'

gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'

gem 'activerecord'
gem 'pry'
gem 'rack-lineprof'
gem 'rack-mini-profiler'

gem 'httpclient'
gem 'worker_cast', github: 'tompng/worker_cast'
