source 'https://rubygems.org'

gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'erubis'

gem 'activerecord'
gem 'pry'
gem 'rack-lineprof'
gem 'rack-mini-profiler'

gem 'httpclient'
gem 'worker_cast', git: 'https://github.com/tompng/worker_cast'
